Fix/ansible lint
marcpires/devops-hands-on pull request #24
Opened 2021-05-07 18:45 UTC by alecio-rocha

Please Review my PR?

2021-05-14 13:49 UTC, marcpires requested changes
LGTM

2021-05-14 13:49 UTC, marcpires commented on infra-as-code/labs/ansible/playbook.yml
> +  - "vars/packages_{{ ansible_os_family | lower }}.yml"
Move this info to role vars

2021-05-14 13:49 UTC, marcpires commented on infra-as-code/labs/ansible/roles/update_environment/README.md
> +Role Name
Doc missing

2021-05-14 13:49 UTC, marcpires commented on infra-as-code/labs/ansible/roles/update_environment/meta/main.yml
> +  description: your role description
Role description

2021-05-14 13:49 UTC, marcpires commented on requirements.txt
> +ansible==3.2.0
Can this file be removed ? As in labs/ansible we have a requiments.txt file

2021-05-18 20:14 UTC, alecio-rocha commented on infra-as-code/labs/ansible/hosts_vars/10.86.133.238
> +ansible_ssh_user: ubuntu
Done

2021-05-18 20:14 UTC, alecio-rocha commented on infra-as-code/labs/ansible/inventory/dev
> +10.76.189.140
Done

2021-05-18 20:14 UTC, alecio-rocha commented on infra-as-code/labs/ansible/README.md
> +$ multipass launch -n ansible-labs -m 15G -d 40G 18.04
Done

2021-05-18 20:14 UTC, alecio-rocha commented on infra-as-code/labs/ansible/playbook.yml
> +  - "vars/packages_{{ ansible_os_family | lower }}.yml"
Done

2021-05-18 20:14 UTC, alecio-rocha commented on infra-as-code/labs/ansible/roles/update_environment/README.md
> +Role Name
Done

2021-05-18 20:15 UTC, alecio-rocha commented on infra-as-code/labs/ansible/roles/update_environment/meta/main.yml
> +  description: your role description
Done

2021-05-18 20:18 UTC, alecio-rocha commented on requirements.txt
> +ansible==3.2.0
Yes, this file to be removed because exist one file in "labs/ansible" with this name.

2021-05-18 20:30 UTC, marcpires requested changes
LGTM. Addresss comments

2021-05-18 20:30 UTC, marcpires commented on infra-as-code/labs/ansible/roles/docker/README.md
> +- **ansible_lsb.id**: Distribution name
Ansible facts vars can be ommited. Old docker package list for CentOS missing

2021-05-18 20:30 UTC, marcpires commented on infra-as-code/labs/ansible/roles/docker/tasks/debian/install_packages.yml
> +    msg: "{{ docker_service }}"
Missing EOF

2021-05-18 20:30 UTC, marcpires commented on infra-as-code/labs/ansible/roles/docker/vars/debian/packages_debian.yml
> +repo_link: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_lsb.codename }} stable"
Missing EOF

2021-05-18 20:30 UTC, marcpires commented on linux/labs/README.md
> +## Linux Hands-on
This file could be present

2021-05-18 20:40 UTC, alecio-rocha commented on linux/labs/README.md
> +## Linux Hands-on
Done

2021-05-18 20:40 UTC, alecio-rocha commented on infra-as-code/labs/ansible/roles/docker/vars/debian/packages_debian.yml
> +repo_link: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_lsb.codename }} stable"
done

2021-05-18 20:40 UTC, alecio-rocha commented on infra-as-code/labs/ansible/roles/docker/tasks/debian/install_packages.yml
> +    msg: "{{ docker_service }}"
done

2021-05-18 20:40 UTC, alecio-rocha commented on infra-as-code/labs/ansible/roles/docker/README.md
> +- **ansible_lsb.id**: Distribution name
done

2021-05-18 20:46 UTC, marcpires approved these changes
LGTM

2021-05-18 20:55 UTC, marcpires approved these changes
LGTM

2021-05-18 20:57 UTC, merged